version: '2'
services:

  # nginx reverse proxy
  nginx:
    container_name: nginx
    build:
      context: ./containers/nginx
    ports:
      - "80:80"
    links:
      - "apache2"
      - "web_app"

  # node web app
  web_app:
    container_name: web_app
    build:
      context: ./containers/web_app
    volumes:
      - ./code/web:/root/app

  # apache2
  apache2:
    container_name: apache2
    build:
      context: ./containers/apache2
    volumes:
      - ./logs/apache2:/var/log/apache2
      - ./code/api:/var/www/html
    links:
      - "db"

  # mysql
  db:
    container_name: db
    build:
      context: ./containers/db
      args:
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    build: ./containers/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32769:80"
    links:
      - "db:db"

  # redis
  redis:
    container_name: redis
    build:
      context: ./containers/redis
    ports:
      - "6379:6379"
        
# Volumes
volumes:
  mysql:
    driver: "local"
